port = "8080"

[db]
hostname = "db"
port = "5432"
tablename = "frogboard"
username = "frogboard"
password = "frogboardpassword"

[redis]
hostname = "redis"
port = "6379"

[filestorage]
type = "fs"

[filestorage.fs]
path = "/var/frogboard/filestorage"