version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FROGBOARD_PORT=80
    ports:
      - 8080:80
    volumes:
      - data:/var/frogboard/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: frogboard
      POSTGRES_PASSWORD: frogboardpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frogboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
      
volumes:
  data:
  db-data:
  redis-data: